'use client';

import Head from "next/head";
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { useEffect } from "react";
import {Properties} from "csstype";

export default function Home() {
    const router = useRouter();
    useEffect(() => { setTimeout( () => router.push('/login'), 2300) });

    const center: Properties = {
        position: 'absolute',
        left: '50%',
        top: '50%',
        transform: 'translate(-50%, -50%)',
    };

    // @ts-ignore
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={center}>
                <Image
                    src="/logo.svg"
                    alt="GoldLux Logo"
                    width={180}
                    height={87}
                    priority
                />
            </main>
        </>
    )
}