'use client';

import Head from "next/head";
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { Password } from 'primereact/password';
import { InputText } from 'primereact/inputtext';
import { Button } from 'primereact/button';
import { Properties } from "csstype";

export default function About() {
  const router = useRouter();
  const [password, setPassword] = useState("");
  const [email, setEmail] = useState("");

  const centerH: Properties = {
    position: 'absolute',
    left: '50%',
    transform: 'translate(-50%, 0%)',
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-center mt-10 font-medium text-gray-500">Prihlasovanie</p>
      <p className="text-center mt-24 text-xl font-bold tracking-tighter">Vitajte v appke GoldLux!</p>
      <div className="" >
        <div style={centerH} className="mt-16">
          <span className="p-float-label">
            <InputText id="email" value={email} onChange={(e) => setEmail(e.target.value)} />
            <label htmlFor="email">Email</label>
          </span>
        </div>
        <div style={centerH} className="mt-[135px]">
          <span className="p-float-label">
            <Password inputId="password" value={password} onChange={(e) => setPassword(e.target.value)} toggleMask
              promptLabel="Zadajte heslo" weakLabel="Slabé" mediumLabel="Priemerné" strongLabel="Silné" />
            <label htmlFor="password">Heslo</label>
          </span>
        </div>
        <div style={centerH}>
          <Button style={{ marginTop: "48vh" }} label="Prihlásiť sa" severity="secondary" outlined />
        </div>
        <div style={centerH}>
          <p style={{ marginTop: "68vh" }} className="mt-20 text-center underline text-gray-600">Alebo, ak ste nový užívateľ, zaregistrujte sa </p>
        </div>

      </div>
    </>
  )
}