import Head from "next/head";
import Image from 'next/image';
import { useRouter } from 'next/router';
import styles from "@/styles/Login.module.css";

export default function About() {
    const router = useRouter();
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p className={styles.title}>Prihlásenie ako zákazník</p>
            <hr className={styles.lineTop}/>
            <p className={styles.text}>Vitajte v appke GoldLux!</p>
            <main className={styles.center}>
                <Image
                    src="/login_img.png"
                    alt="GoldLux Logo"
                    width={238}
                    height={238}
                    priority
                />
            </main>
        </>
    )
}
