import Head from "next/head";
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useEffect } from "react";
import styles from "@/styles/Splash.module.css";

export default function About() {
    const router = useRouter();
    useEffect(() => { setTimeout( () => router.push('/login'), 2300) });
    return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.center}>
            <Image
                src="/logo.svg"
                alt="GoldLux Logo"
                width={180}
                height={87}
                priority
            />
        </main>
    </>
    )
}
